# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8081/solr/osfsufia
test:
  url: http://localhost:8081/solr/osfsufia
production:
  url: http://<%= ENV["SOLR_HOST"] %>:<%= ENV["SOLR_PORT"] %>/solr/osfsufia
