# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8081/solr/osfsufia
test:
  url: http://localhost:8081/solr/osfsufia
production:
  url: http://your.production.server:8080/bl_solr/core0
